sudo: required

language: node_js

node_js:
  - "lts/*"

services:
  - docker

before_install:
  - docker pull drachtio/drachtio-server:latest
  - docker pull drachtio/sipp:latest
  - docker pull drachtio/rtpengine:mr7.1
  - docker pull redis
  - docker images

script:
  - npm test
  